spring:
  application:
    name: Access
  datasource:
    url: jdbc:postgresql://localhost:5432/REQ_LIMIT
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    hikari:
      auto-commit: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop